"""
Merge engine.

This module applies user selections to a diff tree (`DiffNode`) and produces a
single merged JSON-compatible Python object.

The merge process is driven by a diff tree generated by the diff builder.
Each node in the tree corresponds to a canonical node ID and contains per-document
presence/value information plus child nodes for containers.

Core ideas
----------
- Selections are provided as a mapping: node ID -> Selection.
- Selections inherit down the tree: selecting a document at a subtree node acts
  as a default for all descendants unless overridden by a more specific node.
- Object nodes merge by keys (children), array nodes merge by element children.
- Selecting a document where a node is missing deletes that node in the output.
- Leaf nodes with status `same` or `missing` can be auto-resolved safely.
- Leaf nodes with status `diff` require a selection; otherwise they are reported
  as unresolved merge conflicts.
- Nodes where a type error *originates* also require a selection. They are
  identified by `_is_type_error_origin` rather than by status, because
  `type_error` is aggregated upward: an ancestor that merely inherits the status
  is an ordinary container node and must still merge through its children, or
  healthy siblings would be dropped.

Payload note
------------
The diff tree intentionally does not embed full container values (object/array)
in `ValuePresence.value`. Merging therefore relies on recursively merging child
nodes for containers rather than copying container values directly.

Type-error origins are the exception: they have no children to recurse through,
so the diff builder embeds their values and a selection copies one directly.
"""

from typing import Any

from diff_fuse.domain.errors import ConflictUnresolvedError
from diff_fuse.models.diff import DiffNode, DiffStatus, NodeKind, ValuePresence
from diff_fuse.models.merge import MergedNodeRef, MergeSelection

# Sentinel used internally to represent "deleted / not present in merged output".
_MISSING = object()

ResolvedRefByNodeId = dict[str, MergedNodeRef]


def _dedupe_preserve_order(ids: list[str]) -> list[str]:
    """
    De-duplicate ids while preserving their first-seen order.

    Parameters
    ----------
    ids : list[str]
        Input ids.

    Returns
    -------
    list[str]
        De-duplicated ids in stable order.
    """
    seen: set[str] = set()
    out: list[str] = []
    for p in ids:
        if p not in seen:
            seen.add(p)
            out.append(p)
    return out


def _is_type_error_origin(node: DiffNode) -> bool:
    """
    Whether a node is where a type error originates, rather than inheriting one.

    `type_error` is aggregated upward, so every ancestor of a mismatch also
    reports it. Only the originating node is childless -- aggregation requires
    children -- and only it carries an explanatory `message` and embedded
    per-document values.

    Merge must never treat a *propagated* type error as a leaf: doing so would
    drop the whole subtree, healthy siblings included.
    """
    return node.status == DiffStatus.type_error and not node.children


def _pick_present_value(node: DiffNode) -> Any:
    """
    Pick a present value from any document for a node.

    This is only safe when a node is known to be auto-resolvable (status is
    `same` or `missing`). For containers, `ValuePresence.value` is typically
    None, so callers should only use this for scalar leaves unless they
    explicitly accept that limitation.

    Parameters
    ----------
    node : DiffNode
        Diff node to inspect.

    Returns
    -------
    Any
        The first present non-null value, falling back to the first present value
        if every present value is null, or `_MISSING` if none are present.

    Notes
    -----
    Non-null values win because a null may mean "no value" (see `NullMode`), in
    which case the node is auto-resolvable and the document that actually holds a
    value should supply it -- otherwise document ordering alone would decide.

    The test is on `value_type` rather than on the value itself: falsy scalars
    (0, False, "") are real values, and container nodes carry `value=None` with a
    `value_type` of "object"/"array" because container values are not embedded.

    Example
    -------
    For a node with per_doc:
    {
        "a": ValuePresence(present=True, value=5, value_type="number"),
        "b": ValuePresence(present=True, value=5, value_type="number"),
        "c": ValuePresence(present=False, value=None, value_type=None),
    }
    This returns 5 (from doc "a") since it's present, even though "c" is missing.
    """
    for vp in node.per_doc.values():
        if vp.present and vp.value_type != "null":
            return vp.value

    for vp in node.per_doc.values():
        if vp.present:
            return vp.value

    return _MISSING


def _value_for_doc(node: DiffNode, doc_id: str) -> Any:
    """
    Get the selected document's value for a node.

    Parameters
    ----------
    node : DiffNode
        Node to read.
    doc_id : str
        Document identifier.

    Returns
    -------
    Any
        Value for the document at this node, or `_MISSING` if the node is absent
        in that document.

    Notes
    -----
    Container nodes intentionally do not embed values in the diff response, so
    this often returns None for objects/arrays even when present. The merge
    algorithm therefore resolves containers by recursion, not by copying.
    """
    vp: ValuePresence | None = node.per_doc.get(doc_id)
    if vp is None or not vp.present:
        return _MISSING
    return vp.value


def _effective_selection(
    node: DiffNode,
    selections: dict[str, MergeSelection],
    inherited: MergeSelection | None,
) -> MergeSelection | None:
    """
    Determine the selection active at a node.

    Exact node id matches override inherited selections.

    Parameters
    ----------
    node : DiffNode
        Current node.
    selections : dict[str, MergeSelection]
        User selections.
    inherited : MergeSelection | None
        Selection inherited from the nearest ancestor node (if any).

    Returns
    -------
    MergeSelection | None
        The effective selection at this node.

    Example
    -------
    Given selections:
    - "a": doc "A" (with node id instead of path for actual implementation)
    - "a.b.c": doc "B"
    Then:
    - node "a" has effective selection doc "A"
    - node "a.b" has effective selection doc "A" (inherited)
    - node "a.b.c" has effective selection doc "B" (overrides parent)
    - node "a.b.c.d" has effective selection doc "B" (inherits from "a.b.c")
    """
    return selections.get(node.node_id, inherited)


def _merge_object_children(
    node: DiffNode,
    selections: dict[str, MergeSelection],
    inherited: MergeSelection | None,
    unresolved: list[str],
    resolved_ref_by_node_id: ResolvedRefByNodeId,
) -> Any:
    """
    Merge an object node by merging its children.

    Example
    -------
    For an object node with children "x" and "y", this recursively merges "x"
    and "y" and returns a dict like {"x": merged_x, "y": merged_y}, omitting keys that resolve to `_MISSING`.
    """
    out: dict[str, Any] = {}

    for child in node.children:
        merged_child = _merge_node(
            child,
            selections,
            inherited,
            unresolved,
            resolved_ref_by_node_id,
        )

        if merged_child is _MISSING:
            resolved_ref_by_node_id[child.node_id] = MergedNodeRef(present=False)
            continue

        assert child.key is not None
        out[child.key] = merged_child
        resolved_ref_by_node_id[child.node_id] = MergedNodeRef(
            present=True,
            object_key=child.key,
        )

    node_exists_somewhere = any(vp.present for vp in node.per_doc.values())
    return out if node_exists_somewhere else _MISSING


def _merge_array_children(
    node: DiffNode,
    selections: dict[str, MergeSelection],
    inherited: MergeSelection | None,
    unresolved: list[str],
    resolved_ref_by_node_id: ResolvedRefByNodeId,
) -> Any:
    """
    Merge an array node by merging its element children.

    Example
    -------
    For an array node with children representing elements at indices 0, 1, and 2,
    this recursively merges those children and returns a list like [merged_0, merged_1, merged_2].

    The diff builder aligns array elements according to a configured strategy, so
    this function assumes children already reflect that alignment.
    """
    out_list: list[Any] = []

    for child in node.children:
        merged_child = _merge_node(
            child,
            selections,
            inherited,
            unresolved,
            resolved_ref_by_node_id,
        )

        if merged_child is _MISSING:
            resolved_ref_by_node_id[child.node_id] = MergedNodeRef(present=False)
            continue

        idx = len(out_list)
        out_list.append(merged_child)
        resolved_ref_by_node_id[child.node_id] = MergedNodeRef(
            present=True,
            array_index=idx,
        )

    node_exists_somewhere = any(vp.present for vp in node.per_doc.values())
    return out_list if node_exists_somewhere else _MISSING


def _apply_selection_to_node(
    node: DiffNode,
    sel: MergeSelection,
    selections: dict[str, MergeSelection],
    unresolved: list[str],
    resolved_ref_by_node_id: ResolvedRefByNodeId,
) -> Any:
    """
    Apply a selection to a node.

    Manual selections always produce a value and stop recursion.
    Document selections either delete the node (if missing in the chosen doc),
    or act as an inherited default for containers so deeper overrides remain possible.

    Example
    -------
    For a node ID with path "a.b.c" and selection doc "A", this picks the value from doc "A" at that node.
    If the node is an object and doc "A" doesn't exist at that path, this returns `_MISSING` (i.e., the
    node is deleted). If the node is an object and doc "A" does exist, this recursively merges children with
    doc "A" as the inherited selection, allowing for deeper manual overrides.
    """
    if sel.kind == "manual":
        return sel.manual_value

    assert sel.doc_id is not None
    chosen = _value_for_doc(node, sel.doc_id)
    if chosen is _MISSING:
        return _MISSING

    # A type-error origin has no children to recurse into, and embeds its values,
    # so the chosen document's value is the answer -- including for containers.
    if _is_type_error_origin(node):
        return chosen

    if node.kind == NodeKind.object:
        return _merge_object_children(
            node,
            selections,
            inherited=sel,
            unresolved=unresolved,
            resolved_ref_by_node_id=resolved_ref_by_node_id,
        )

    if node.kind == NodeKind.array:
        return _merge_array_children(
            node,
            selections,
            inherited=sel,
            unresolved=unresolved,
            resolved_ref_by_node_id=resolved_ref_by_node_id,
        )

    return chosen


def _merge_node(
    node: DiffNode,
    selections: dict[str, MergeSelection],
    inherited: MergeSelection | None,
    unresolved: list[str],
    resolved_ref_by_node_id: ResolvedRefByNodeId,
) -> Any:
    """
    Merge a single node recursively.

    Example
    -------
    For a node with path "a.b.c", this determines the effective selection at that path
    (e.g., doc "A" from "a.b.c" or inherited doc "A" from "a.b"), applies it, and returns the merged value.
    If no selection is active, this returns `_MISSING`. For an object node with no selection, this recursively
    merges children and returns a dict. For an array node with no selection, this recursively merges children
    and returns a list.
    """
    sel = _effective_selection(node, selections, inherited)

    if sel is not None:
        return _apply_selection_to_node(
            node,
            sel,
            selections,
            unresolved,
            resolved_ref_by_node_id,
        )

    # A type-error origin needs an explicit selection. Checked before the kind
    # dispatch below, because such a node can have kind=array (a failed array
    # strategy) and would otherwise merge to [] instead of being reported.
    if _is_type_error_origin(node):
        unresolved.append(node.node_id)
        return _MISSING

    # Dispatch on kind alone: a childless container is still a container, and must
    # merge to {} / [] rather than falling through to the scalar path (where
    # `_pick_present_value` would return the intentionally omitted container value).
    if node.kind == NodeKind.object:
        return _merge_object_children(
            node,
            selections,
            inherited=None,
            unresolved=unresolved,
            resolved_ref_by_node_id=resolved_ref_by_node_id,
        )

    if node.kind == NodeKind.array:
        return _merge_array_children(
            node,
            selections,
            inherited=None,
            unresolved=unresolved,
            resolved_ref_by_node_id=resolved_ref_by_node_id,
        )

    if node.status in (DiffStatus.same, DiffStatus.missing):
        return _pick_present_value(node)

    unresolved.append(node.node_id)
    return _MISSING


def _merge_from_diff_tree_detailed(
    root: DiffNode,
    selections: dict[str, MergeSelection],
    *,
    raise_on_conflict: bool,
) -> tuple[Any, list[str], ResolvedRefByNodeId]:
    """
    Detailed version of merge that also tracks resolved node references.
    It returns:
    - merged output
    - unresolved node ids
    - resolved refs by node id
    """
    unresolved: list[str] = []
    resolved_ref_by_node_id: ResolvedRefByNodeId = {}

    merged = _merge_node(
        root,
        selections,
        inherited=None,
        unresolved=unresolved,
        resolved_ref_by_node_id=resolved_ref_by_node_id,
    )

    unresolved = _dedupe_preserve_order(unresolved)

    merged_out = {} if merged is _MISSING else merged

    # Root is always represented explicitly for completeness.
    resolved_ref_by_node_id[root.node_id] = MergedNodeRef(
        present=(merged is not _MISSING),
    )

    if unresolved and raise_on_conflict:
        raise ConflictUnresolvedError(unresolved)

    return merged_out, unresolved, resolved_ref_by_node_id


def try_merge_from_diff_tree_with_refs(
    root: DiffNode,
    selections: dict[str, MergeSelection],
) -> tuple[Any, list[str], ResolvedRefByNodeId]:
    """
    Best-effort merge that never raises and also returns merged-node refs.

    Parameters
    ----------
    root : DiffNode
        Root node of the diff tree.
    selections : dict[str, MergeSelection]
        User merge selections.

    Returns
    -------
    tuple[Any, list[str], ResolvedRefByNodeId]
        (merged_output, unresolved, resolved_ref_by_node_id)
        - merged_output is the best-effort merged JSON structure.
        - unresolved lists canonical node IDs that still require resolution.
        - resolved_ref_by_node_id maps canonical node IDs to their location in the merged output.

    Notes
    -----
    This helper is convenient for API endpoints that want to always return a
    payload while still reporting unresolved conflicts and resolved node references to the client.
    """
    return _merge_from_diff_tree_detailed(
        root,
        selections,
        raise_on_conflict=False,
    )
