"""
Session state model.

This module defines the canonical server-side representation of a session.
A session groups a set of input documents together with their parse/normalization
results so that diff and merge operations can be performed without repeatedly
processing raw inputs.
"""

from datetime import datetime

from pydantic import Field

from diff_fuse.api.dto.base import APIModel
from diff_fuse.models.document import DocumentResult, InputDocument, RootInput


class Session(APIModel):
    """
    Server-side session state.

    A session represents a working set of documents uploaded by a client.
    It stores both the original inputs and their parsed/normalized results
    so that downstream operations (diff, merge, export, suggestions) can
    execute without re-parsing raw content.

    Attributes
    ----------
    session_id : str
        Opaque unique identifier for the session. Generated by the backend.
    created_at : datetime
        UTC timestamp when the session was created.
    updated_at : datetime
        UTC timestamp of the last access. Used for TTL/sliding expiration.
    documents : list[InputDocument]
        Original client-provided document descriptors.
        These are preserved primarily for traceability and potential reprocessing.
    documents_results : list[DocumentResult]
        Per-document parse and normalization results.
        - The order corresponds to the original input order.
        - Entries with ``ok=False`` indicate parse/validation failures.
        - Successful entries contain the normalized document structure.
    """

    session_id: str
    created_at: datetime
    updated_at: datetime
    documents: list[InputDocument] = Field(default_factory=list)
    documents_results: list[DocumentResult] = Field(default_factory=list)

    @property
    def root_inputs(self) -> dict[str, RootInput]:
        """
        Build the diff-ready root input mapping.

        Returns
        -------
        dict[str, RootInput]
            Mapping from ``doc_id`` to the tuple expected by the diff engine:
            ``(present: bool, normalized_value: Any | None)``.

        Notes
        -----
        This is a **derived view** computed from ``documents_results`` and is
        intentionally not stored to avoid duplication and staleness.
        """
        return {dr.doc_id: dr.build_root_input() for dr in self.documents_results}
